id: AC20A6428
title: Aspirations in Accordance with the Dharma
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.007593
  last_modified_at: 2022-02-28 22:59:37.007597
