id: AC20A6428
title: Aspiration for Rebirth in Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.001660
  last_modified_at: 2022-02-28 22:59:37.001670
