id: AC20A6428
title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara, the
  Glorious Victor, to Avert the Final War'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.025690
  last_modified_at: 2022-02-28 22:59:37.025713
