id: AC20A6428
title: Prayer to the Gurus of the Dzogchen Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.015941
  last_modified_at: 2022-02-28 22:59:37.015944
