id: AC20A6428
title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.014632
  last_modified_at: 2022-02-28 22:59:37.014635
