id: AC20A6428
title: A Brief Ritual for Consecrating Representations of Enlightened Body, Speech
  and Mind
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:36.997914
  last_modified_at: 2022-02-28 22:59:36.997920
