id: AC20A6428
title: Prayer to Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.011783
  last_modified_at: 2022-02-28 22:59:37.011785
