id: AC20A6428
title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.009359
  last_modified_at: 2022-02-28 22:59:37.009361
