id: AC20A6428
title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.020044
  last_modified_at: 2022-02-28 22:59:37.020052
