id: AC20A6428
title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
  Female Practice'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.027001
  last_modified_at: 2022-02-28 22:59:37.027004
