id: AC20A6428
title: Prayer to Buddha AmitÄbha
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:59:37.013053
  last_modified_at: 2022-02-28 22:59:37.013056
